//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVolve.DataTableTools.Revit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eVolve.DataTableTools.Revit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table
        ///Tools.
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string ColumnInfoName_DataType {
            get {
                return ResourceManager.GetString("ColumnInfoName_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string ColumnInfoName_Expression {
            get {
                return ResourceManager.GetString("ColumnInfoName_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnInfoName_Name {
            get {
                return ResourceManager.GetString("ColumnInfoName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ColumnInfoName_Order {
            get {
                return ResourceManager.GetString("ColumnInfoName_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more values were not able to be converted to the target type.
        ///The default value of &quot;{0}&quot; was set as the data in these rows.
        ///
        ///This operation can be undone by using the Undo function within Revit..
        /// </summary>
        internal static string CouldNotConvertValueWarning {
            get {
                return ResourceManager.GetString("CouldNotConvertValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eVolve Electrical.
        /// </summary>
        internal static string eVolveElectrical {
            get {
                return ResourceManager.GetString("eVolveElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eVolve Mechanical.
        /// </summary>
        internal static string eVolveMechanical {
            get {
                return ResourceManager.GetString("eVolveMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column &apos;{0}&apos; was not found in {1} &apos;{2}&apos;..
        /// </summary>
        internal static string ExportColumnNotFoundError {
            get {
                return ResourceManager.GetString("ExportColumnNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failure.
        /// </summary>
        internal static string FileLoadFailure {
            get {
                return ResourceManager.GetString("FileLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failure.
        /// </summary>
        internal static string FileSaveFailure {
            get {
                return ResourceManager.GetString("FileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_Medium_20x20 {
            get {
                object obj = ResourceManager.GetObject("Help_Medium_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SQL Select statement which will be used to populate the selected {0}. The SQL results will be used to define the column names and their respective data type..
        /// </summary>
        internal static string ImportStatementPromptInfo {
            get {
                return ResourceManager.GetString("ImportStatementPromptInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} entries are defined..
        /// </summary>
        internal static string NoEntriesDefinedError {
            get {
                return ResourceManager.GetString("NoEntriesDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} is selected..
        /// </summary>
        internal static string NoValueSelectedError {
            get {
                return ResourceManager.GetString("NoValueSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this produces an error, the operation will cancel..
        /// </summary>
        internal static string OperationCancelsOnErrorNotice {
            get {
                return ResourceManager.GetString("OperationCancelsOnErrorNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed..
        /// </summary>
        internal static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This will delete ALL saved configuration data.
        ///Would you like to continue?.
        /// </summary>
        internal static string ResetEntireConfigPrompt {
            get {
                return ResourceManager.GetString("ResetEntireConfigPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete saved configuration for the selected {0}?.
        /// </summary>
        internal static string ResetSelectedDataTableConfigPrompt {
            get {
                return ResourceManager.GetString("ResetSelectedDataTableConfigPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_20x20 {
            get {
                object obj = ResourceManager.GetObject("Settings_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load settings file:.
        /// </summary>
        internal static string SettingsLoadErrorNotice {
            get {
                return ResourceManager.GetString("SettingsLoadErrorNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings file:.
        /// </summary>
        internal static string SettingsSaveErrorNotice {
            get {
                return ResourceManager.GetString("SettingsSaveErrorNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This operation will completely overwrite the structure and contents the selected {0} and rebuild with the {1} selections.
        ///
        ///Would you like to continue?.
        /// </summary>
        internal static string SQLImportConfirmationPrompt {
            get {
                return ResourceManager.GetString("SQLImportConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SQL statement to execute after importing data..
        /// </summary>
        internal static string StatementToRunAfterImport {
            get {
                return ResourceManager.GetString("StatementToRunAfterImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SQL statement to execute prior to importing data..
        /// </summary>
        internal static string StatementToRunPriorToImport {
            get {
                return ResourceManager.GetString("StatementToRunPriorToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced tools for working with {0} Data Tables..
        /// </summary>
        internal static string ToolTipText {
            get {
                return ResourceManager.GetString("ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for &apos;{0}&apos;..
        /// </summary>
        internal static string ValueMustBeProvided1Error {
            get {
                return ResourceManager.GetString("ValueMustBeProvided1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string ValueMustBeProvided2Error {
            get {
                return ResourceManager.GetString("ValueMustBeProvided2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for &apos;{0}&apos;, &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string ValueMustBeProvided3Error {
            get {
                return ResourceManager.GetString("ValueMustBeProvided3Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be provided for &apos;{0}&apos; when enabled..
        /// </summary>
        internal static string ValueMustBeProvidedWhenEnabledError {
            get {
                return ResourceManager.GetString("ValueMustBeProvidedWhenEnabledError", resourceCulture);
            }
        }
    }
}
