<Project>
  <PropertyGroup>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RunCodeAnalysis>false</RunCodeAnalysis>     
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>    
    <EnableDefaultItems>false</EnableDefaultItems>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <LangVersion>14</LangVersion>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <RevitYear Condition="$(Configuration.Contains('Revit 2024'))">2024</RevitYear>
    <RevitYear Condition="$(Configuration.Contains('Revit 2025'))">2025</RevitYear>
    <RevitYear Condition="$(Configuration.Contains('Revit 2026'))">2026</RevitYear>
	<RevitYear Condition="$(Configuration.Contains('Revit 2027'))">2027</RevitYear>
    
    <DefineConstants>$(DefineConstants);REVIT$(RevitYear)</DefineConstants>
    <DefineConstants Condition="'$(RevitYear)' == '2025' or '$(RevitYear)' == '2026' or '$(RevitYear)' == '2027'">$(DefineConstants);CORE</DefineConstants>
        
    <EvolvePrefix Condition="$(Configuration.Contains('eE'))">eE</EvolvePrefix>
    <EvolveProduct Condition="$(Configuration.Contains('eE'))">Electrical</EvolveProduct>
    
    <EvolvePrefix Condition="$(Configuration.Contains('eM'))">eM</EvolvePrefix> 
    <EvolveProduct Condition="$(Configuration.Contains('eM'))">Mechanical</EvolveProduct>
        
    <DefineConstants Condition="$(Configuration.Contains('eE'))">$(DefineConstants);ELECTRICAL</DefineConstants>
    <DefineConstants Condition="$(Configuration.Contains('eM'))">$(DefineConstants);MECHANICAL</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
	<OutputPath>bin\$(EvolvePrefix) Debug Revit $(RevitYear)\</OutputPath>
	<DefineConstants>$(DefineConstants);TRACE;DEBUG;CODE_ANALYSIS</DefineConstants>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <OutputPath>bin\Release\</OutputPath>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RevitYear)' == '2024'">
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RevitYear)' == '2025' or '$(RevitYear)' == '2026'">
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RevitYear)' == '2027'">
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="$(DefineConstants.Contains('CORE'))">
    <UseWPF>True</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>
</Project>