//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVolve.CsvDataExchange.Revit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eVolve.CsvDataExchange.Revit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Data
        ///Exchange.
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files.
        /// </summary>
        internal static string CsvFiles {
            get {
                return ResourceManager.GetString("CsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during processing..
        /// </summary>
        internal static string ErrorOccurredNotice {
            get {
                return ResourceManager.GetString("ErrorOccurredNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eVolve Electrical.
        /// </summary>
        internal static string eVolveElectrical {
            get {
                return ResourceManager.GetString("eVolveElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eVolve Mechanical.
        /// </summary>
        internal static string eVolveMechanical {
            get {
                return ResourceManager.GetString("eVolveMechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string ExportColumn_ProjectName {
            get {
                return ResourceManager.GetString("ExportColumn_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Number.
        /// </summary>
        internal static string ExportColumn_ProjectNumber {
            get {
                return ResourceManager.GetString("ExportColumn_ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date/Time.
        /// </summary>
        internal static string ExportColumn_Timestamp {
            get {
                return ResourceManager.GetString("ExportColumn_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string ExportColumn_UserName {
            get {
                return ResourceManager.GetString("ExportColumn_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation Name.
        /// </summary>
        internal static string ExportColumn_WorkstationName {
            get {
                return ResourceManager.GetString("ExportColumn_WorkstationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Completed.
        /// </summary>
        internal static string ExportCompleted {
            get {
                return ResourceManager.GetString("ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV Data.
        /// </summary>
        internal static string ExportCsvData {
            get {
                return ResourceManager.GetString("ExportCsvData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failure.
        /// </summary>
        internal static string FileLoadFailure {
            get {
                return ResourceManager.GetString("FileLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failure.
        /// </summary>
        internal static string FileSaveFailure {
            get {
                return ResourceManager.GetString("FileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_Medium_20x20 {
            get {
                object obj = ResourceManager.GetObject("Help_Medium_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Completed.
        /// </summary>
        internal static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV Data.
        /// </summary>
        internal static string ImportCsvData {
            get {
                return ResourceManager.GetString("ImportCsvData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please address the following issues:.
        /// </summary>
        internal static string IssuesMustBeAddressedNotice {
            get {
                return ResourceManager.GetString("IssuesMustBeAddressedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file contained no usable data..
        /// </summary>
        internal static string NoDataNotice {
            get {
                return ResourceManager.GetString("NoDataNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements were selected..
        /// </summary>
        internal static string NoElementsSelectedNotice {
            get {
                return ResourceManager.GetString("NoElementsSelectedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load settings file:.
        /// </summary>
        internal static string SettingsLoadErrorNotice {
            get {
                return ResourceManager.GetString("SettingsLoadErrorNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings file:.
        /// </summary>
        internal static string SettingsSaveErrorNotice {
            get {
                return ResourceManager.GetString("SettingsSaveErrorNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single {0} must be selected..
        /// </summary>
        internal static string SingleValueMustBeSelectedError {
            get {
                return ResourceManager.GetString("SingleValueMustBeSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports/Exports data from Revit using the {0} Integration Platform..
        /// </summary>
        internal static string ToolTipText {
            get {
                return ResourceManager.GetString("ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Id.
        /// </summary>
        internal static string UniqueId {
            get {
                return ResourceManager.GetString("UniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Errors.
        /// </summary>
        internal static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} must be selected..
        /// </summary>
        internal static string ValueMustBeSelectedError {
            get {
                return ResourceManager.GetString("ValueMustBeSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When {0} is selected, the folder location in {1} must exist..
        /// </summary>
        internal static string WhenXSelectedFolderYMustExistError {
            get {
                return ResourceManager.GetString("WhenXSelectedFolderYMustExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When {0} is selected, {1} must exist..
        /// </summary>
        internal static string WhenXSelectedYMustExistError {
            get {
                return ResourceManager.GetString("WhenXSelectedYMustExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} element(s) processed..
        /// </summary>
        internal static string XElementsProcessedNotice {
            get {
                return ResourceManager.GetString("XElementsProcessedNotice", resourceCulture);
            }
        }
    }
}
